// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro_Detalle2_Ap2.DAL;

namespace Registro_Detalle2_Ap2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuplidorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("OrdenID");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suplidor")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuplidorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OrdenID");

                    b.HasIndex("SuplidorID");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<double>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<decimal>("ValorInventario")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Concepto = "Arroz",
                            Costo = 22m,
                            Existencia = 0.0,
                            ValorInventario = 10m
                        },
                        new
                        {
                            ProductoId = 2,
                            Concepto = "Azucar",
                            Costo = 50m,
                            Existencia = 0.0,
                            ValorInventario = 6m
                        },
                        new
                        {
                            ProductoId = 3,
                            Concepto = "Chocolate",
                            Costo = 25m,
                            Existencia = 0.0,
                            ValorInventario = 20m
                        });
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SuplidorID");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorID = 1,
                            Nombres = "Ramon",
                            ProductoId = 0
                        },
                        new
                        {
                            SuplidorID = 2,
                            Nombres = "Pablo",
                            ProductoId = 0
                        },
                        new
                        {
                            SuplidorID = 3,
                            Nombres = "Cristian",
                            ProductoId = 0
                        });
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("Registro_Detalle2_Ap2.Models.Ordenes", null)
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("OrdenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registro_Detalle2_Ap2.Models.Suplidores", null)
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("SuplidorID");
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.Ordenes", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });

            modelBuilder.Entity("Registro_Detalle2_Ap2.Models.Suplidores", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
